# Generated by Django 5.1.3 on 2025-10-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringmodel',
            name='string',
        ),
        migrations.AddField(
            model_name='stringmodel',
            name='value',
            field=models.CharField(default='value', max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stringmodel',
            name='id',
            field=models.UUIDField(),
        ),
    ]
