# Generated by Django 5.1.3 on 2025-10-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_remove_stringmodel_string_stringmodel_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringmodel',
            name='value',
            field=models.CharField(default='', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
